plot "output1.dat", 
    "output2.dat",
    "output3.dat",
    "output4.dat",
    "output5.dat",
    "output6.dat",
    "output7.dat",
    "output8.dat",
    "output9.dat",
    "output10.dat",
    "output11.dat",
    "output12.dat",
    "output13.dat",
    "output14.dat",
    "output15.dat",
    "output16.dat",
    "output17.dat",
    "output18.dat",
    "output19.dat",
    "output20.dat"
pause -1